global using Microsoft.Extensions.DependencyInjection;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using Microsoft.Extensions.Configuration;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using System.Linq.Expressions;
global using Microsoft.Extensions.Hosting;
global using MediatR;